version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      microsoft-dotnet:
        patterns:
          - "Microsoft.*"

  - package-ecosystem: docker
    directories:
      - /src/Accounts/Accounts.Api
      - /src/Gateway/BankFlow.Gateway
      - /src/Identity/BankFlow.Identity.Api
      - /src/Transfers/Transfers.Api
      - /src/Web/bankflow-web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
