<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../Contracts/BankFlow.Contracts/BankFlow.Contracts.csproj" />
    <ProjectReference Include="../Accounts.Application/Accounts.Application.csproj" />
    <ProjectReference Include="../Accounts.Domain/Accounts.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>
</Project>
