<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>BankFlow.Identity.Api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../BuildingBlocks/BankFlow.ServiceDefaults/BankFlow.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
</Project>
